export const INCREMENT_COUNTER='INCREMENT_COUNTER';
export const DECREMENT_COUNTER='DECREMENT_COUNTER';


export const GET_MEDICINE='GET_MEDICINE';
export const ADD_MEDICINE='ADD_MEDICINE';
export const UPDATE_MEDICINE='UPDATE_MEDICINE';
export const DELETE_MEDICINE='DELETE_MEDICINE';
export const LOADING_MEDICINE='LOADING_MEDICINE';
export const ERROR_MEDICINE='ERROR_MEDICINE';
export const ADD_TO_CART='ADD_TO_CART';
export const INDEX_CART='INDEX_CART';
export const INCREMENT_CART='INCREMENT_CART';
export const DECREMENT_CART='DECREMENT_CART';
export const DELETE_CART='DELETE_CART';
export const ADD_TO_WISHLIST='ADD_TO_WISHLIST';
export const DELETE_WISHLIST='DELETE_WISHLIST';


export const GET_DEPARTMENT='GET_DEPARTMENT';
export const ADD_DEPARTMENT='ADD_DEPARTMENT';
export const DELETE_DEPARTMENT='DELETE_DEPARTMENT';
export const UPDATE_DEPARTMENT='UPDATE_DEPARTMENT';




