export const INCREMENT_COUNTER='INCREMENT_COUNTER';
export const DECREMENT_COUNTER='DECREMENT_COUNTER';

export const GET_MEDICINE='GET_MEDICINE';
export const ADD_MEDICINE='ADD_MEDICINE';
export const UPDATE_MEDICINE='UPDATE_MEDICINE';
export const DELETE_MEDICINE='DELETE_MEDICINE';
export const LOADING_MEDICINE='LOADING_MEDICINE';

export const GET_DEPARTMENT='GET_DEPARTMENT';
export const ADD_DEPARTMENT='ADD_DEPARTMENT';
export const DELETE_DEPARTMENT='DELETE_DEPARTMENT';
export const UPDATE_DEPARTMENT='UPDATE_DEPARTMENT';

